
# Configuration
# --------------------------------------

source $HOME/.zsh/config/variables.zsh
source $HOME/.zsh/config/aliases.zsh
source $HOME/.zsh/config/functions.zsh

plugins=(git)
source $ZSH/oh-my-zsh.sh
[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
